name: "DEV DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      enviroment: prod
      aws-assume-role-arn: "arn:aws:iam::627844880550:role/github-actions-cadu220-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "cadu220-sa-east-1-terraform-statefile-4"
      aws-lock-dynamodb-table: "cadu220-eat-1-terraform-lock"